version: '2.2'
services:
  proj-db:
    container_name: 'proj-db-container'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: tonitonitoni
      MYSQL_USER: root
      MYSQL_DATABASE: project_dev
    ports:
      - 3307:3306
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD"
      interval: 20s
      retries: 10
      timeout: 5s


  proj-code:
    container_name: 'proj-code-container'
    restart: always
    depends_on:
      proj-db:
        condition: service_healthy
    build: 
      context: .
    ports:
      - 8089:3000
    

     # project-db-mongo:
  #   container_name: project-db-mongo-container
  #   image: mongo
  #   volumes:
  #     - /data/mongodb/db:/data/db
  #   ports:
  #     - "27018:27017"